#!/bin/bash 

# Use bash because of better control over fids.

lock_file="${1}"
id="${2}"

echo "VB2: ${VERBOSE_INDENT}Entering atomic_echo_3 with lock_file=${lock_file} and id=${id}"

flock_lock_file="${lock_file}.flock"

exit_status=0

set -o noclobber

(
    if [[ $USE_IVI_FLOCK -eq 1 ]]; then 
        ${IVI_FLOCK} -x -n 9 || exit 1
    fi 

    echo "${id}" 1> "${lock_file}"

    if [[ $? -ne 0 ]]; then exit_status=1; fi

) 9>${flock_lock_file}

if [[ $? -ne 0 ]]; then exit_status=1; fi

${IVI_RM} "${flock_lock_file}"

echo "VB2: ${VERBOSE_INDENT}Leaving atomic_echo_3 with lock_file ${lock_file} and id=${id} with status=${exit_status}"

exit ${exit_status}

