#!/bin/tcsh -f

# set echo 

echo " "

cat /dev/null > Include_lines/test_instances
if (${status}) exit 1 

set top_dir = `pwd`

set test_program = "$<"
while ("${test_program}" != "") 
        pushd "test_input/${test_program}" > /dev/null 
            if (${status}) then
                ${P_STDERR} " "
                ${P_STDERR} "Script build_test_depend_2 unable to change to directory test_input/${test_program} from directory `pwd`."
                exit 1
            endif 

            set test_instances = `find . -maxdepth 1 -mindepth 1 -type d \! \( -name '.*' \) |& sed 's#./##'`

            if ("${test_instances}" == "") then
                if  ($?CREATE_TEST_DIRS) then
                    ${IVI_MKDIR} NULL
                    if ${status} exit 1

                    set test_instance = NULL
                    
                    echo "Makefile-test-depend: test_input/${test_program}/${test_instance}"
                    if (${status}) exit 1 

                    echo "${test_program} ${test_instance}" >> ${top_dir}/Include_lines/test_instances
                    if (${status}) exit 1 
                endif  
            else
                foreach test_instance (${test_instances})
                    echo "Makefile-test-depend: test_input/${test_program}/${test_instance}"
                    if (${status}) exit 1 

                    echo "${test_program} ${test_instance}" >> ${top_dir}/Include_lines/test_instances
                    if (${status}) exit 1 
                end
            endif 
        popd > /dev/null
    endif 

    set test_program = "$<"
end

