#!/bin/tcsh -f

###############################################################################
#
# Identification:
#     A script to build the file Makefile-libs-needed
#
# Description:
#     This script builds the file Makefile-libs-needed (technically,
#     Include_lines/Makefile-libs-needed/Makefile-libs-needed${VAR_CACHE_SUFFIX}) 
#     in the directory given by the first parameter, or the current directory if
#     there are no parameters. 
#
#     This script implements file locking for build_makefile_libs_needed_2 which
#     does the work. 
#
# Author:
#     Kobus Barnard
#
###############################################################################

if ($?IVI_SET_ECHO) then
    set echo    
endif 

@ num_args = ${#argv}

if ("${num_args}" > 1) then
    ${P_STDERR} "Script build_makefile_libs_needed takes only  0 or 1 parameters."
    exit 1
endif 

##########################################################

if ($?IVI_VERBOSE_INDENT) then
    setenv IVI_VERBOSE_INDENT "    ${IVI_VERBOSE_INDENT}"
else 
    setenv IVI_VERBOSE_INDENT ""
endif 

##########################################################

set build_dir = ""

if ("${num_args}" >= 1) then
    if ("${1}" != "") then
        set build_dir = `echo ${1} | sed 's/ *//g'`
    endif 
endif 

if ("${build_dir}" != "") then
    set build_dir = `echo ${build_dir} | sed 's#//*#/#g' | sed 's#/$##'`
    cd ${build_dir} 
endif 

${MAKE_SCRIPT_PATH}ivi_lock ${MAKE_SCRIPT_PATH}build_makefile_libs_needed_2 $* 
exit ${status}


