#!/bin/tcsh -f

${MAKE_SCRIPT_PATH}stream_file_names -s -m > Makefile-program-targets
if (${status}) exit ${status}
# ${IVI_CP} Makefile-program-targets Makefile-program-targets-SAVE

${IVI_CP} Makefile-program-targets Makefile-bin-targets
if (${status}) exit ${status}

${IVI_CP} Makefile-program-targets Makefile-program-targets-depend
if (${status}) exit ${status}

${IVI_RM} .Makefile-bin-targets.swp
${VIM_FOR_MAKE} < ${MAKE_EDIT_PATH}Bin.${VIM_SUFFIX} Makefile-bin-targets >& /dev/null
if (${status}) exit ${status}

${IVI_RM} .Makefile-program-targets.swp
${VIM_FOR_MAKE} < ${MAKE_EDIT_PATH}Programs.${VIM_SUFFIX} Makefile-program-targets >& /dev/null
if (${status}) exit ${status}

${IVI_RM} .Makefile-program-targets-depend.swp
${VIM_FOR_MAKE} < ${MAKE_EDIT_PATH}Programs_depend.${VIM_SUFFIX} Makefile-program-targets-depend >& /dev/null
if (${status}) exit ${status}

${IVI_CAT} Makefile-program-targets-depend >> Makefile-program-targets
if (${status}) exit ${status}

${MAKE_SCRIPT_PATH}stream_file_names -s -m -v | sed '/\<version\.[ch][px]*\>/d' > Makefile-obj-targets
if (${status}) exit ${status}
# ${IVI_CP} Makefile-obj-targets Makefile-obj-targets-SAVE

${IVI_CP} Makefile-obj-targets Makefile-local-obs
if (${status}) exit ${status}

${IVI_RM} .Makefile-local-obs.swp
${VIM_FOR_MAKE} < ${MAKE_EDIT_PATH}Local_obs.${VIM_SUFFIX} Makefile-local-obs >& /dev/null
if (${status}) exit ${status}
# ${IVI_CP} Makefile-local-obs Makefile-local-obs-SAVE

${IVI_RM} .Makefile-obj-targets.swp
${VIM_FOR_MAKE} < ${MAKE_EDIT_PATH}Dirs.${VIM_SUFFIX} Makefile-obj-targets >& /dev/null
if (${status}) exit ${status}
# ${IVI_CP} Makefile-obj-targets Makefile-obj-targets-SAVE-2

${IVI_CP} Makefile-obj-targets Makefile-obj-targets-depend
if (${status}) exit ${status}
# ${IVI_CP} Makefile-obj-targets-depend Makefile-obj-targets-depend-SAVE

${IVI_RM} .Makefile-obj-targets.swp
${VIM_FOR_MAKE} < ${MAKE_EDIT_PATH}Obs.${VIM_SUFFIX} Makefile-obj-targets >& /dev/null
if (${status}) exit ${status}
# ${IVI_CP} Makefile-obj-targets Makefile-obj-targets-SAVE-3

${IVI_CAT} Makefile-local-obs >> Makefile-program-targets
if (${status}) exit ${status}
${IVI_CAT} Makefile-obj-targets >> Makefile-program-targets
if (${status}) exit ${status}

#   Breaking style here a bit. We could have used a vim script, but instead we use
#   a regular script.
${MAKE_SCRIPT_PATH}stream_prog_lib_obs >> Makefile-program-targets
if (${status}) exit ${status}

${IVI_RM} .Makefile-obj-targets-depend.swp
${VIM_FOR_MAKE} < ${MAKE_EDIT_PATH}Obs_depend.${VIM_SUFFIX} Makefile-obj-targets-depend >& /dev/null
if (${status}) exit ${status}
# ${IVI_CP} Makefile-obj-targets-depend Makefile-obj-targets-depend-SAVE-2

${IVI_CAT} Makefile-obj-targets-depend >> Makefile-program-targets
if (${status}) exit ${status}

${IVI_RM} Makefile-obj-targets-depend
${IVI_RM} Makefile-local-obs
${IVI_RM} Makefile-obj-targets
#
${MAKE_SCRIPT_PATH}stream_file_names -s -m -v | sed -n '/\<version\.[ch][px]*\>/p' > Makefile-version-obj-targets
if (${status}) exit ${status}
# ${IVI_CP} Makefile-version-obj-targets Makefile-version-obj-targets-SAVE

${IVI_RM} .Makefile-version-obj-targets.swp
${VIM_FOR_MAKE} < ${MAKE_EDIT_PATH}Dirs.${VIM_SUFFIX} Makefile-version-obj-targets >& /dev/null
if (${status}) exit ${status}
# ${IVI_CP} Makefile-version-obj-targets Makefile-version-obj-targets-SAVE-2

${VIM_FOR_MAKE} < ${MAKE_EDIT_PATH}Version_obs.${VIM_SUFFIX} Makefile-version-obj-targets >& /dev/null
${IVI_CAT} Makefile-version-obj-targets >> Makefile-program-targets
if (${status}) exit ${status}

${IVI_ECHO} " " >> Makefile-program-targets
${IVI_ECHO} " " >> Makefile-program-targets

${IVI_RM} Makefile-version-obj-targets

${IVI_CP} Include_lines/help_files  Makefile-help-targets
if (${status}) exit ${status}
${VIM_FOR_MAKE} < ${MAKE_EDIT_PATH}Dirs.${VIM_SUFFIX} Makefile-help-targets >& /dev/null
if (${status}) exit ${status}
${VIM_FOR_MAKE} < ${MAKE_EDIT_PATH}Help.${VIM_SUFFIX} Makefile-help-targets >& /dev/null
if (${status}) exit ${status}
${IVI_ECHO} " " >> Makefile-help-targets
${IVI_CAT} Include_lines/help_files | ${IVI_SED} 's/\(.*\)\.help/$(MAKE_DOC_DIR)\1.1 : $(MAKE_DOC_DIR)\1\.help.1#+$(IVI_CP) $< $@#/' | tr '#+' '\n\t'  >> Makefile-help-targets
if (${status}) exit ${status}

${IVI_CP} Include_lines/writeup_files  Makefile-writeup-targets
if (${status}) exit ${status}
${VIM_FOR_MAKE} < ${MAKE_EDIT_PATH}Dirs.${VIM_SUFFIX} Makefile-writeup-targets >& /dev/null
if (${status}) exit ${status}
${VIM_FOR_MAKE} < ${MAKE_EDIT_PATH}Writeup.${VIM_SUFFIX} Makefile-writeup-targets >& /dev/null
if (${status}) exit ${status}
${IVI_ECHO} " " >> Makefile-writeup-targets
${IVI_CAT} Include_lines/writeup_files | ${IVI_SED} 's/\(.*\)\.w/$(MAKE_DOC_DIR)\1.1 : $(MAKE_DOC_DIR)\1\.w.1#+$(IVI_CP) $< $@#/' | tr '#+' '\n\t' >> Makefile-writeup-targets
if (${status}) exit ${status}

${IVI_CP} Include_lines/script_files  Makefile-script-targets
if (${status}) exit ${status}
# ${IVI_CP} Makefile-script-targets Makefile-script-targets-1
${IVI_RM} .Makefile-script-targets.swp
${VIM_FOR_MAKE} < ${MAKE_EDIT_PATH}Dirs.${VIM_SUFFIX} Makefile-script-targets >& /dev/null
if (${status}) exit ${status}
# ${IVI_CP} Makefile-script-targets Makefile-script-targets-2
${VIM_FOR_MAKE} < ${MAKE_EDIT_PATH}Script.${VIM_SUFFIX} Makefile-script-targets >& /dev/null
if (${status}) exit ${status}
# ${IVI_CP} Makefile-script-targets Makefile-script-targets-3
${IVI_ECHO} " " >> Makefile-script-targets
${IVI_CAT} Include_lines/script_files | ${IVI_SED} 's/\(.*\)/$(MAKE_DOC_DIR)\1.1 : $(MAKE_DOC_DIR)\1\.shell.1#+$(IVI_CP) $< $@#/' | tr '#+' '\n\t' >> Makefile-script-targets
if (${status}) exit ${status}
# ${IVI_CP} Makefile-script-targets Makefile-script-targets-4

${IVI_CAT} /dev/null > Makefile-depend-headers 
if (${status}) exit ${status}
${MAKE_SCRIPT_PATH}ivi_makedepend '' -c -Y -w20000 -DMAKE_DEPEND  -DMAKE_DEPEND_GEN_H ${PROG_BASE_INCLUDES}  > Makefile-depend-src 
if (${status}) exit ${status}
${MAKE_SCRIPT_PATH}ivi_makedepend '' -x -Y -w20000 -DMAKE_DEPEND  -DMAKE_DEPEND_GEN_H ${PROG_BASE_INCLUDES}  >> Makefile-depend-src 
if (${status}) exit ${status}

${IVI_ECHO} " " > Makefile-depend
${IVI_ECHO} "#" >> Makefile-depend
${IVI_ECHO} "# Machine generated file to set make targets" >> Makefile-depend
${IVI_ECHO} "#" >> Makefile-depend
${IVI_ECHO} " " >> Makefile-depend

${IVI_CAT} Makefile-program-targets Makefile-bin-targets Makefile-help-targets Makefile-writeup-targets Makefile-script-targets Makefile-depend-headers Makefile-depend-src >> Makefile-depend 
if (${status}) exit ${status}

${IVI_RM} Makefile-bin-targets
${IVI_RM} Makefile-program-targets
${IVI_RM} Makefile-program-targets-depend
${IVI_RM} Makefile-help-targets
${IVI_RM} Makefile-writeup-targets
${IVI_RM} Makefile-script-targets
${IVI_RM} Makefile-depend-headers
${IVI_RM} Makefile-depend-src
