#!/bin/tcsh -f 

set found = 0
set IVI_SRC_PATH = ""

pushd `pwd` > /dev/null

while ("`pwd`" != "/")
    if (-e Make/init_machine) then
        set found = 1
        break
    endif 

    set IVI_SRC_PATH = "../${IVI_SRC_PATH}"

    cd ..
end

popd > /dev/null

if (${found}) then
    if ("${IVI_SRC_PATH}" == "") then
        set IVI_SRC_PATH = "./"
    endif 
else
    set IVI_SRC_PATH = "${HOME}/src/"

   if (! -e ${IVI_SRC_PATH}Make/init_machine) then
       # We cannot use P_STDERR here because we might not have defined it yet.
       bash -c "echo 1>&2"
       bash -c "echo This directory does not seem to be below a src dirctory with IVI installed. 1>&2"
       bash -c "echo Nor does ${IVI_SRC_PATH}Make/init_machine exist.  1>&2"
       bash -c "echo 1>&2"

       exit 1 
   endif 
endif 

source ${IVI_SRC_PATH}/Make/init_machine >& /dev/null

setenv IVI_SRC_PATH "${IVI_SRC_PATH}" 

#setenv IVI_VERBOSE
source ${IVI_SRC_PATH}/Make/init_compile >& /dev/null

echo ${IVI_LD_PATH}
setenv IVI_LD_PATH ${IVI_LD_PATH}

