#!/bin/tcsh -f

##############################################################################
#
# Identification:
#     Prints path modification time in human readable format
#
# Description:
#     This script prints the modification time of its argument in human readable
#     format in one second resolution. Its main use is for debugging. Kobus
#     also has a script "get_mod_time" that returns higher resolution
#     modification times as integers that are suitable for comparisons. If
#     needed, that script can become part of the Make/script scripts. 
#
#     We implement this versiion using "/bin/date -r" when avalable, but provide
#     sensible error messages if the arugment is not an existing path. The
#     program "date" is seriously broken as the flag "-r" has two meanings, and
#     if the argument does not exist, it will try to convert it to an integral
#     value for seconds, and when that inevitably fails, it will give you an
#     obtuse error message.
#
# Author:
#     Kobus Barnard 
#
##############################################################################

if ($# != 1) then
    echo  "Script get_mod_time needs exactly one argument."
    ${P_STDERR} "Script $0 needs exactly one argument."
    exit 1
else if (! -e "${1}") then
    ${P_STDERR} "Argument $1 to $0 does not exist."
    exit 1
else 
    # Portable enough? We can also use IVI_STAT. 
    ${IVI_DATE} -r "$1"
endif 

