#!/bin/tcsh

# This script must be run in your src directory. Typically, that is $HOME/src,
# but it need not be, especially if you feel the need to have multiple versions.
# If you run this script in a different directory, then it will create some
# files and directories that you will need to remove. 
#
# This script relies on the fact that svn check out also serves fine as svn
# update. 
#
svn co svn+ssh://vision.cs.arizona.edu/home/svn/src/Make/trunk Make
svn co svn+ssh://vision.cs.arizona.edu/home/svn/src/lib/trunk lib
svn co svn+ssh://vision.cs.arizona.edu/home/svn/src/include_before/trunk include_before
svn co svn+ssh://vision.cs.arizona.edu/home/svn/src/include_after/trunk include_after
svn co svn+ssh://vision.cs.arizona.edu/home/svn/src/IVI/trunk IVI
svn co svn+ssh://vision.cs.arizona.edu/home/svn/src/IVI_cpp/trunk IVI_cpp
svn co svn+ssh://vision.cs.arizona.edu/home/svn/src/tools/trunk tools
