#!/bin/tcsh -f

# We assume that we have sourced init_compile. 

set num_iterations = 10 

@ num_args = ${#argv}

if ($num_args > 0) then
    set num_iterations = $1
endif 

@ iteration = 0

${VERBOSE_ECHO} "Process $$ doing test_ivi_lock_2_helper."

while ($iteration < $num_iterations)
    @ iteration += 1
    ${VERBOSE_ECHO} "Process $$ doing iteration ${iteration} / ${num_iterations}"

    ${LOCK_PROGRAM} 200 ./increment_file_line NULL $$

    if (${status}) then 
        ${P_STDERR} "Command failed: ${LOCK_PROGRAM} 200 ./increment_file_line NULL $$"
        exit 1 
    endif 

    echo proc $$ finished iteration ${iteration}
end 

echo proc $$ done ${num_iterations} iterations.


