#!/bin/tcsh -f

# We assume that we have sourced init_compile. 

set num_iterations = 10 

@ num_args = ${#argv}

if ($num_args > 0) then
    set num_iterations = $1
endif 

@ iteration = 0

while ($iteration < $num_iterations)
    @ iteration += 1
    echo proc $$ doing iteration $iteration
    ${LOCK_PROGRAM} 60 ./increment_file_line 

    if (${status}) then 
        ${P_STDERR} "Command failed: ${LOCK_PROGRAM} 30 ./increment_file_line"
        exit 1 
    endif 

    echo proc $$ finished iteration $iteration
end 


