#!/bin/tcsh -f

# We assume that we have sourced init_compile. 

if (! $?MILLI_SLEEP_PROG) then
    setenv MILLI_SLEEP_PROG ${MAKE_SCRIPT_PATH}ivi_echo_pid
endif 

set exit_status = 0
set output_file = test_ivi_milli_sleep.output

${IVI_CREATE} "${output_file}"
if ($status) exit 1

@ count=1 

set start_time = `date +%H:%M:%S`

while ($count < 10000) 
    ${MILLI_SLEEP_PROG} >>  "${output_file}"
    @ count+=1
end 
    
set end_time = `date +%H:%M:%S`

if (${exit_status}) then
    echo "Make_ivi: Script test_ivi_milli_sleep failed." 
    echo "    Start time: ${start_time}"
    echo "    End time:   ${end_time}"
    echo " "
    exit ${exit_status}
else 
    echo "Make_ivi: Script make_ivi finished successfully." 
    echo "    Start time: ${start_time}"
    echo "    End time:   ${end_time}"
    echo " "
endif 






