#!/bin/tcsh -f

# Not recently TESTED, but quite a few changes have been made! 

##################################################################################
#
# Build script for imported libraries and utilities where mimimal build
# infrastracture exists. Unless the code is very simple, usually there is some
# infrastructure, and typically we want to leverage that using a different
# script (perhaps yet to be written). However: 
#    For code that comes with "configure", use the template build_with_configure
#    For code that comes with "cmake", use the template build_with_cmake
#
# ================================================================================
#
# This file started its life as a copy of 
#     ${IVI_SRC_PATH}/Make/scripts/build_imported
# Typically it gets renamed as "build" or "build_ivilab". Sometimes it gets some
# tweaks for the particular libraries. 
#
# The file
#     ${IVI_SRC_PATH}/Make/scripts/build_imported
# is a template for a build script for imported library code which comes with
# some makefiles which we typically move to Makefile-2, and tweak. Having done
# that, we can (optionally) add a copy of  ${IVI_SRC_PATH}/Make/scripts/Makefile. 
#
#
# This file is generally called by "make". It can also be called directly. The
# main purpose is to normalize the make environment, and to implement some
# functionality that is difficult to do in a robust portable way for all flavors
# of make. 
#
# The chief functionallity implemented here is to determine the value of
# IVI_SRC_PATH, and then call build-2 to continue setting up the environment,
# and the call make with "-f Makefile-2", but often that part will
# be replaced with the specific commands for the imported package. We tell
# build-2 not to build additional makefiles by setting IVI_SKIP_DEPEND.
#
##################################################################################

# This next part is shared by all files in Make whose names begin with "build",
# AND scripts ivi_add_makefiles, create_library, create_program, and
# update_ivi_core. Updates should be propogated. 

# We want to use a pure "cd".
unalias cd
    
if ($?FORCE_IVI_SRC_DIR) then 
    if (-e "${FORCE_IVI_SRC_DIR}/Make/init_compile") then 
        setenv IVI_SRC_PATH "${FORCE_IVI_SRC_DIR}"
    else 
        bash -c 'echo "Env var FORCE_IVI_SRC_DIR is set to ${FORCE_IVI_SRC_DIR}, but ${FORCE_IVI_SRC_DIR}/Make/init_compile does not exist." >&2'
        exit 1 
    endif 
else  
    # Use env var for IVI_DIRS for better error reporting via bash sub-shell.
    if ($?FORCE_IVI_DIR) then
        setenv IVI_DIRS "${FORCE_IVI_DIR}"
    else
        setenv IVI_DIRS ". kjb KJB ivi IVI src"
    endif 

    # Find out where we are in the source tree. In particular, we want to find a
    # directory that has one of the directories in IVI_DIRS as a subdir, which
    # itself has Make as a sub-dir and Make/init_compile as a file in that. 

    # We want to block going above the user's home directory because it might cause
    # a mount request that we don't want. If we are not below their home, then it is
    # fine to ga to the root. 
    #
    pushd ${HOME} >& /dev/null
    set home_pwd = `pwd`
    popd >& /dev/null

    set found = 0
    set ivi_top = ""

    pushd `pwd` > /dev/null

    while (("`pwd`" != "/") && ("`pwd`" != "${home_pwd}")) 
        foreach ivi_dir (${IVI_DIRS}) 
            if ("${ivi_dir}" == ".") then
                set ivi_dir = ""
            else
                set ivi_dir = "${ivi_dir}/"
            endif 

            if (-e "${ivi_dir}Make/init_compile") then
                set found = 1
                break
            endif 
        end

        if (${found}) break

        set ivi_top = "../${ivi_top}"
        cd ..
    end

    popd > /dev/null

    if (${found}) then
        if ("${ivi_dir}" == "") then
            set ivi_dir = "./"
        endif 

        setenv IVI_SRC_PATH "${ivi_top}${ivi_dir}"
    else 
        setenv THIS_PROGRAM "$0" 

        # We cannot use P_STDERR here because we might not have defined it yet.
        bash -c 'echo " " >&2'
        bash -c 'echo "This directory is not below a directory with IVI installed." >&2'
        bash -c 'echo "Valid directories for IVI in this context: ${IVI_DIRS}." >&2'
        bash -c 'echo "To experiment with a temporary fix, try setting FORCE_IVI_SRC_DIR." >&2'
        bash -c 'echo "For a more permanent fix, edit this program: " >&2'
        bash -c 'echo "    ${THIS_PROGRAM} " >&2'
        bash -c 'echo "or contact Kobus." >&2'
        bash -c 'echo " " >&2'

        exit 1
    endif 
endif 

pushd ${IVI_SRC_PATH} > /dev/null
    setenv IVI_SRC_PATH "${cwd}/"
popd > /dev/null

###############################################################################

# Check that this file ($0) is up to date compared to the reference one.
set need_to_replace_myself = `${IVI_SRC_PATH}Make/scripts/test_older_than "$0" "${IVI_SRC_PATH}Make/build"`
     
if (${need_to_replace_myself}) then
    # We could make this even more automated using the defunct script
    # self_update, but this is too fancy. It cannot do the rebuild in parallel,
    # and we would want to implement checking for infinite recursion.  Using
    # self_update is commented out here:
    #     exec ${IVI_SRC_PATH}Make/scripts/self_update "$0" "${IVI_SRC_PATH}Make/build" Make

    echo "Script $0 is attempting to rebuild itself."
    echo "You will need to reenter your build command (e.g., make or $0)."
    exec /bin/cp "${IVI_SRC_PATH}Make/build" "$0"
endif 

setenv IVI_SKIP_DEPEND
setenv IVI_SKIP_DIR_MADE
source ${IVI_SRC_PATH}Make/scripts/build-2 



